# List of devices
# Each device has a name, a class (type of device), a path and an id
devices:
  - name: candidate
    class: INGA
    path: /dev/ttyUSB1
    id: 0x2

  - name: reference
    class: INGA
    path: /dev/ttyUSB0
    id: 0x1

